version: '4'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
